[package]
name = "api_tool_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["json", "native-tls"] }
tokio = { version = "1.0", features = ["full"] }
dialoguer = "0.10.4"
urlencoding = "2.1.3"
serde_json = "1.0"
dotenv = "0.15"

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = 'abort'
strip = true